# Site settings
author: Mtthew Enbar
title: Matthew's Coding Blog
header-img: img/home-bg.png
email: matthew.enbar@gmail.com
copyright_name: Mtthew Enbar
description: > # this means to ignore newlines until "baseurl:"
  And adventure of coding through quarantine and hopefully soon after
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mattenbar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
